import type { Metadata } from "next";
import "./globals.css";
import { NextAuthProvider } from "./sessionProvider";

export const metadata: Metadata = {
  title: "Paradox | IIT Madras | BS Degree",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className="bg-[#F6F1EC]">
          {children}
        </body>
      </NextAuthProvider>
    </html>
  );
}
